# Generated by Django 5.2.1 on 2025-05-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
